version: '3.8'
services:
  client:
    build: client
    ports:
      - '3000:1234'
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build: api
    ports:
      - '5000:5000'
